package DTO;
// Generated 05-Jan-2016 19:04:10 by Hibernate Tools 4.3.1



/**
 * Testtable2 generated by hbm2java
 */
public class Testtable2  implements java.io.Serializable {


     private int id;
     private String name;

    public Testtable2() {
    }

	
    public Testtable2(int id) {
        this.id = id;
    }
    public Testtable2(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


